// export const FEATURED_IDEAS =
//   [
//     {
//       id: { $oid: '64a1b2c3d4e5f67890123456' },
//       title: 'Smart Health Planner',
//       category: 'Health Tech',
//       stage: 'Concept',
//       description: 'A daily health planner powered by AI to track nutrition, workouts and mental wellness routines.',
//       details: 'Use intelligent reminders, nutrition tracking and mood monitoring to keep users on track with healthy habits. Built for busy people who want actionable wellness guidance.',
//       problem: 'Many wellness apps only track one dimension of health, leaving users without a unified holistic plan.',
//       solution: 'Combine nutrition, fitness, sleep, and mental wellness into one guided daily experience with adaptive AI coaching.',
//       targetMarket: 'Busy professionals, fitness enthusiasts, and people seeking better work-life balance.',
//       revenueModel: 'Freemium app with premium coaching plans, in-app health courses, and partner wellness product recommendations.',
//       competitors: 'Traditional fitness trackers, meal planners, and standalone meditation apps.',
//       impact: 'Improves daily consistency, reduces decision fatigue, and encourages healthier routines through personalized habit support.',
//       image: 'slide1',
//       tags: ['AI', 'Health', 'Productivity'],
//       features: ['AI-driven guidance', 'Daily habit tracking', 'Personalized recommendations'],
//       metrics: ['30% faster habit adoption', 'Daily check-ins with mood scoring', '30+ wellness exercises'],
//       comments: [
//         { id: 'c1', author: 'Aida', message: 'This planner could really help make healthy habits stick.', date: '2026-05-10' },
//         { id: 'c2', author: 'Mina', message: 'I would love an option to sync workouts and meals automatically.', date: '2026-05-12' },
//       ],
//     },
//     {
//       id: { $oid: '64a1b2c3d4e5f67890123457' },
//       title: 'Community Growth Platform',
//       category: 'Social',
//       stage: 'Early beta',
//       description: 'A platform that helps creators and communities grow with collaborative tools and reward systems.',
//       details: 'Bring creators and fans closer through shared goals, exclusive content, and engagement boosts. The platform makes it easy to launch challenges, reward contributors, and track community momentum.',
//       problem: 'Current creator platforms are fragmented and make it hard to build meaningful engagement beyond likes.',
//       solution: 'Offer collaborative goal-setting, participation incentives, and community analytics in one place.',
//       targetMarket: 'Creators, small communities, and brands seeking deeper engagement with followers.',
//       revenueModel: 'Subscription tiers for creators, branded challenges, and transaction fees on fan rewards.',
//       competitors: 'Discord communities, creator subscription tools, and social challenge apps.',
//       impact: 'Helps communities grow healthier engagement and delivers measurable creator monetization pathways.',
//       image: 'slide2',
//       tags: ['Creators', 'Community', 'Engagement'],
//       features: ['Creator tools', 'Reward systems', 'Community analytics'],
//       metrics: ['50% higher participation in creator challenges', 'Custom reward experiences', 'Real-time engagement dashboards'],
//       comments: [
//         { id: 'c3', author: 'Noah', message: 'Community challenges would be a huge win for engagement.', date: '2026-05-11' },
//       ],
//     },
//     {
//       id: { $oid: '64a1b2c3d4e5f67890123458' },
//       title: 'Eco-Commerce Marketplace',
//       category: 'Sustainability',
//       stage: 'Launch ready',
//       description: 'A marketplace for eco-friendly brands with built-in sustainability scoring and transparent sourcing.',
//       details: 'Help conscious shoppers find vetted products and learn where their purchases come from. Each vendor receives sustainability badges and sourcing details for complete transparency.',
//       problem: 'Shoppers struggle to verify eco claims and discover truly sustainable products in crowded marketplaces.',
//       solution: 'Surface trusted eco-friendly brands with clear environmental impact scores and sourcing stories.',
//       targetMarket: 'Environmentally-conscious shoppers, sustainable brands, and impact investors.',
//       revenueModel: 'Marketplace commissions, premium store placement, and sustainability certification services.',
//       competitors: 'General e-commerce marketplaces and green shopping directories.',
//       impact: 'Increases visibility for ethical brands and makes sustainable shopping easier for consumers.',
//       image: 'slide3',
//       tags: ['Green', 'Marketplace', 'Ethical'],
//       features: ['Sustainability scoring', 'Transparent sourcing', 'Curated eco brands'],
//       metrics: ['200+ vetted brands', 'Verified sourcing stories', 'Eco ratings for every product'],
//       comments: [
//         { id: 'c6', author: 'Jade', message: 'Transparency scores would be great for eco shoppers.', date: '2026-05-13' },
//       ],
//     },
//     {
//       id: { $oid: '64b2c3d4e5f678901234abcd' },
//       title: 'Microlearning Studio',
//       category: 'EdTech',
//       stage: 'MVP',
//       description: 'Bite-sized interactive lessons optimized for daily learning.',
//       details: 'Deliver 3–5 minute lessons with spaced repetition, quick quizzes, and community streaks to help learners form lasting habits.',
//       problem: 'Long courses and low completion rates make learning ineffective for busy users.',
//       solution: 'Micro-courses with active recall and social accountability to boost retention.',
//       targetMarket: 'Lifelong learners, professionals, and remote teams.',
//       revenueModel: 'Subscription and team licenses.',
//       competitors: 'Mini-course apps and flashcard platforms.',
//       impact: 'Increases daily learning engagement and measurable skill retention.',
//       image: 'slide1',
//       tags: ['Learning', 'Micro', 'Retention'],
//       features: ['Spaced repetition', 'Micro-quizzes', 'Team leaderboards'],
//       metrics: ['80% weekly retention', '5-minute average lesson time'],
//       comments: [
//         { id: 'c7', author: 'Priya', message: 'Quick lessons like these fit my schedule perfectly.', date: '2026-05-15' },
//       ],
//     },
//     {
//       id: { $oid: '64b2c3d4e5f678901234abce' },
//       title: 'Local Skills Exchange',
//       category: 'Community',
//       stage: 'Prototype',
//       description: 'A neighborhood skill-sharing platform for bartering time and expertise.',
//       details: 'Connect neighbors to trade skills (e.g., guitar lessons for gardening help) and build local resilience.',
//       problem: 'Talents and time are siloed; communities lack simple ways to exchange skills.',
//       solution: 'A reputation-based local exchange with simple booking and trust signals.',
//       targetMarket: 'Local communities and civic groups.',
//       revenueModel: 'Transaction fees and local sponsor partnerships.',
//       competitors: 'Local classifieds and neighbor apps.',
//       impact: 'Strengthens community ties and redistributes practical skills.',
//       image: 'slide2',
//       tags: ['Local', 'Skills', 'Barter'],
//       features: ['Reputation', 'Scheduling', 'Trusted reviews'],
//       metrics: ['High local engagement', 'Low churn by reciprocity'],
//       comments: [
//         { id: 'c8', author: 'Eli', message: 'I love the idea of swapping skills with neighbors.', date: '2026-05-16' },
//       ],
//     },
//     {
//       id: { $oid: '64b2c3d4e5f678901234abcf' },
//       title: 'Personal Carbon Assistant',
//       category: 'Climate Tech',
//       stage: 'Beta',
//       description: 'Track and reduce your carbon footprint with actionable daily tips.',
//       details: 'Integrates receipts, commuting, and device usage to create a pragmatic reduction plan and offset marketplace.',
//       problem: 'Individuals lack simple, personalized actions to reduce emissions effectively.',
//       solution: 'Personalized nudges and verified offset recommendations.',
//       targetMarket: 'Eco-conscious consumers.',
//       revenueModel: 'Affiliate offsets and premium insights.',
//       competitors: 'Carbon trackers and offset marketplaces.',
//       impact: 'Enables measurable personal emissions reductions and community campaigns.',
//       image: 'slide3',
//       tags: ['Climate', 'Sustainability', 'Personal'],
//       features: ['Receipt parsing', 'Commuting insights', 'Offset marketplace'],
//       metrics: ['KG CO2 reduced per user', 'Monthly action completions'],
//       comments: [
//         { id: 'c4', author: 'Sara', message: 'Carbon tracking with receipts is a nice, practical touch.', date: '2026-05-14' },
//       ],
//     },
//     {
//       id: { $oid: '64b2c3d4e5f678901234abd0' },
//       title: 'Voice-First Notes',
//       category: 'Productivity',
//       stage: 'Launch',
//       description: 'Capture and organize thoughts using natural voice commands.',
//       details: 'Voice shortcuts to tag, summarize and turn ideas into tasks using on-device NLP.',
//       problem: 'Note workflows are fragmented and slow when typing on the go.',
//       solution: 'Make voice the primary interface with robust organization tools.',
//       targetMarket: 'Mobile professionals and creators.',
//       revenueModel: 'Freemium with cloud sync.',
//       competitors: 'Voice memo apps and note-taking tools.',
//       impact: 'Speeds up capture and reduces cognitive overhead.',
//       image: 'slide1',
//       tags: ['Voice', 'Notes', 'NLP'],
//       features: ['On-device NLP', 'Tagging', 'Task conversion'],
//       metrics: ['Minutes saved per week', 'Capture frequency'],
//       comments: [
//         { id: 'c9', author: 'Zoe', message: 'Voice commands would make note-taking so much easier during meetings.', date: '2026-05-17' },
//       ],
//     },
//     {
//       id: { $oid: '64b2c3d4e5f678901234abd1' },
//       title: 'Freelance Finance Kit',
//       category: 'FinTech',
//       stage: 'MVP',
//       description: 'Simplified invoicing, taxes and cash flow for independent workers.',
//       details: 'Automated invoices, estimated taxes, and revenue smoothing tools for unpredictable income.',
//       problem: 'Freelancers struggle with taxes and irregular cash flows.',
//       solution: 'A tailored financial toolkit for self-employed creators and contractors.',
//       targetMarket: 'Freelancers and gig workers.',
//       revenueModel: 'Subscription and payment fees.',
//       competitors: 'Accounting tools and invoicing apps.',
//       impact: 'Reduces late payments and improves financial planning.',
//       image: 'slide2',
//       tags: ['Finance', 'Freelance', 'Invoicing'],
//       features: ['Auto-invoicing', 'Tax estimator', 'Cash flow smoothing'],
//       metrics: ['Average days-to-get-paid', 'Tax accuracy improvements'],
//       comments: [
//         { id: 'c10', author: 'Ana', message: 'This would be a game changer for independent contractors.', date: '2026-05-18' },
//       ],
//     },
//     {
//       id: { $oid: '64b2c3d4e5f678901234abd2' },
//       title: 'AR Interior Studio',
//       category: 'Design',
//       stage: 'Prototype',
//       description: 'Preview furniture and layouts in AR before you buy.',
//       details: 'Combine AR visualization with local vendor checkout and style recommendations.',
//       problem: 'Customers often return furniture due to poor fit or style mismatch.',
//       solution: 'Visualize items in your space and get exact fit checks.',
//       targetMarket: 'Home shoppers and interior designers.',
//       revenueModel: 'Affiliate sales and premium design services.',
//       competitors: 'AR shopping tools and design consultancies.',
//       impact: 'Reduces returns and increases confidence in purchases.',
//       image: 'slide3',
//       tags: ['AR', 'Design', 'Commerce'],
//       features: ['Room scanning', 'Fit checker', 'Style suggestions'],
//       metrics: ['Return rate reduction', 'Conversion uplift'],
//       comments: [
//         { id: 'c11', author: 'Maya', message: 'AR previews would make buying furniture so much less stressful.', date: '2026-05-19' },
//       ],
//     },
//     {
//       id: { $oid: '64b2c3d4e5f678901234abd3' },
//       title: 'Senior Companion App',
//       category: 'Health',
//       stage: 'Early beta',
//       description: 'Simple daily check-ins and activity prompts for older adults.',
//       details: 'Schedules reminders, medication prompts and family notifications with large-type UI.',
//       problem: 'Many seniors struggle with complex health apps and isolation.',
//       solution: 'A gentle, human-centered interface for daily wellbeing and family peace-of-mind.',
//       targetMarket: 'Seniors and caregivers.',
//       revenueModel: 'Subscription and caregiver tools.',
//       competitors: 'Care platforms and remote monitoring tools.',
//       impact: 'Improves adherence to routines and reduces caregiver stress.',
//       image: 'slide1',
//       tags: ['Senior', 'Care', 'Health'],
//       features: ['Medication reminders', 'Large UI', 'Family alerts'],
//       metrics: ['Adherence rates', 'Caregiver satisfaction'],
//       comments: [
//         { id: 'c12', author: 'Iris', message: 'A senior-friendly check-in app would help my grandparents a lot.', date: '2026-05-20' },
//       ],
//     },
//     {
//       id: { $oid: '64b2c3d4e5f678901234abd4' },
//       title: 'Supply Chain Trace',
//       category: 'Logistics',
//       stage: 'Concept',
//       description: 'Transparent, blockchain-backed provenance for supply chains.',
//       details: 'Provide immutable product histories, batch tracking and compliance reporting for ethical sourcing.',
//       problem: 'Lack of verifiable provenance damages trust and creates compliance burdens.',
//       solution: 'End-to-end traceability with easy supplier onboarding.',
//       targetMarket: 'Retailers and manufacturers.',
//       revenueModel: 'SaaS for enterprises.',
//       competitors: 'Enterprise traceability vendors.',
//       impact: 'Enables trust and reduces recalls through better data.',
//       image: 'slide2',
//       tags: ['Supply', 'Trace', 'Blockchain'],
//       features: ['Batch tracking', 'Immutable ledger', 'Compliance exports'],
//       metrics: ['Trace coverage %', 'Time-to-trace reduction'],
//       comments: [
//         { id: 'c13', author: 'Noel', message: 'Immutable provenance would solve so many sourcing issues.', date: '2026-05-21' },
//       ],
//     },
//     {
//       id: { $oid: '64b2c3d4e5f678901234abd5' },
//       title: 'Campus Safety Network',
//       category: 'Safety',
//       stage: 'Pilot',
//       description: 'Real-time incident reporting and safe-route guidance for campuses.',
//       details: 'Anonymous reporting, staff dispatch integration, and community alerts to improve on-campus safety.',
//       problem: 'Incident reporting is slow and fragmented on large campuses.',
//       solution: 'Unified reporting with geo-based safe routing.',
//       targetMarket: 'Universities and corporate campuses.',
//       revenueModel: 'Institution subscriptions.',
//       competitors: 'Safety apps and incident management tools.',
//       impact: 'Faster responses and safer navigation across large spaces.',
//       image: 'slide3',
//       tags: ['Safety', 'Campus', 'Geo'],
//       features: ['Anonymous tips', 'Dispatch integration', 'Safe-route mapping'],
//       metrics: ['Response time', 'Reported incidents resolved'],
//       comments: [
//         { id: 'c14', author: 'Rita', message: 'Safe-route guidance would make campuses feel more secure.', date: '2026-05-22' },
//       ],
//     },
//     {
//       id: { $oid: '64b2c3d4e5f678901234abd6' },
//       title: 'Meal-Prep AI',
//       category: 'Food',
//       stage: 'Launch',
//       description: 'Personalized weekly meal plans and shopping lists powered by preferences.',
//       details: 'Auto-generate recipes, scale servings and export to local grocery delivery partners.',
//       problem: 'People struggle to consistently cook healthy meals during busy weeks.',
//       solution: 'Smart meal planning with delivery integration and dietary filters.',
//       targetMarket: 'Busy families and health-conscious shoppers.',
//       revenueModel: 'Affiliate grocery delivery and premium plans.',
//       competitors: 'Meal-kit services and recipe apps.',
//       impact: 'Saves time and reduces food waste with tailored plans.',
//       image: 'slide1',
//       tags: ['Food', 'AI', 'Meal'],
//       features: ['Auto plans', 'Delivery links', 'Diet filters'],
//       metrics: ['Meals generated per week', 'Waste reduction %'],
//       comments: [
//         { id: 'c15', author: 'Tina', message: 'Automatic meal planning would save me hours each week.', date: '2026-05-23' },
//       ],
//     },
//     {
//       id: { $oid: '64b2c3d4e5f678901234abd7' },
//       title: 'Mental Fitness Gym',
//       category: 'Wellness',
//       stage: 'Prototype',
//       description: 'Daily cognitive workouts to improve focus and creativity.',
//       details: 'Short exercises mixing puzzles, breathwork, and creativity prompts with progress tracking.',
//       problem: 'Cognitive fatigue reduces productivity and creativity over time.',
//       solution: 'Structured daily practice that fits into short breaks.',
//       targetMarket: 'Knowledge workers and students.',
//       revenueModel: 'Subscription and enterprise wellness bundles.',
//       competitors: 'Brain-training apps and meditation tools.',
//       impact: 'Improves focus metrics and creative output over time.',
//       image: 'slide2',
//       tags: ['Mental', 'Fitness', 'Focus'],
//       features: ['Daily workouts', 'Progress tracking', 'Community challenges'],
//       metrics: ['Focus score improvements', 'Streak retention'],
//       comments: [
//         { id: 'c16', author: 'Liam', message: 'I would try this for quick focus boosts between meetings.', date: '2026-05-24' },
//       ],
//     },
//     {
//       id: { $oid: '64b2c3d4e5f678901234abd8' },
//       title: 'Tiny Homes Marketplace',
//       category: 'Real Estate',
//       stage: 'Concept',
//       description: 'Buy, customize and finance tiny homes with modular add-ons.',
//       details: 'End-to-end marketplace with architects, financing and placement services for compact living.',
//       problem: 'High housing costs and complex tiny-home procurement limit adoption.',
//       solution: 'Bundle design, financing and local installation into one service.',
//       targetMarket: 'Affordable housing seekers and eco builders.',
//       revenueModel: 'Marketplace fees and financing partnerships.',
//       competitors: 'Modular home vendors and marketplaces.',
//       impact: 'Expands access to affordable, sustainable housing options.',
//       image: 'slide3',
//       tags: ['Housing', 'Tiny', 'Modular'],
//       features: ['Design bundles', 'Financing', 'Installation'],
//       metrics: ['Homes matched', 'Financing approvals'],
//       comments: [
//         { id: 'c5', author: 'Leo', message: 'The tiny homes marketplace sounds perfect for eco-conscious buyers.', date: '2026-05-15' },
//       ],
//     },
//     {
//       id: { $oid: '64b2c3d4e5f678901234abd9' },
//       title: 'Smart Inventory Assistant',
//       category: 'Retail',
//       stage: 'Beta',
//       description: 'Automated stock predictions and restock alerts for small retailers.',
//       details: 'Use sales history and local trends to recommend optimal reorder quantities.',
//       problem: 'Small shops often overstock or run out of bestsellers.',
//       solution: 'Forecasting tailored to low-data retailers with simple recommendations.',
//       targetMarket: 'Independent retailers and cafes.',
//       revenueModel: 'Subscription and marketplace referrals.',
//       competitors: 'Retail analytics and ERP tools.',
//       impact: 'Reduces stockouts and overstock costs for small businesses.',
//       image: 'slide1',
//       tags: ['Retail', 'Inventory', 'Forecasting'],
//       features: ['Demand forecasting', 'Alerts', 'Vendor recommendations'],
//       metrics: ['Stockout reduction', 'Inventory turnover'],
//       comments: [
//         { id: 'c17', author: 'Demi', message: 'This would help small shops avoid costly stockouts.', date: '2026-05-25' },
//       ],
//     },
//     {
//       id: { $oid: '64b2c3d4e5f678901234abda' },
//       title: 'Inclusive Hiring Toolkit',
//       category: 'HR Tech',
//       stage: 'MVP',
//       description: 'Bias-reducing job descriptions and structured interview guides.',
//       details: 'Templates, anonymized screening and scorecards to improve hiring fairness.',
//       problem: 'Bias in hiring reduces diversity and misses great candidates.',
//       solution: 'Practical tooling that integrates into existing workflows to improve outcomes.',
//       targetMarket: 'HR teams and startups.',
//       revenueModel: 'Subscription per seat.',
//       competitors: 'HR software and recruiting tools.',
//       impact: 'Improves diversity and hiring quality with measurable signals.',
//       image: 'slide2',
//       tags: ['HR', 'Hiring', 'Diversity'],
//       features: ['Anonymized screening', 'Scorecards', 'Template library'],
//       metrics: ['Diversity uplift', 'Time-to-hire'],
//       comments: [
//         { id: 'c18', author: 'Nina', message: 'Structured interviews would really help reduce bias.', date: '2026-05-26' },
//       ],
//     },
//     {
//       id: { $oid: '64b2c3d4e5f678901234abdb' },
//       title: 'Offline-first EduKits',
//       category: 'Education',
//       stage: 'Pilot',
//       description: 'Preloaded education kits for low-connectivity areas.',
//       details: 'Harness offline-first content distribution that syncs progress when online.',
//       problem: 'Limited connectivity prevents reliable access to digital education.',
//       solution: 'Deliver robust learning experiences that work offline and sync later.',
//       targetMarket: 'Developing regions and field programs.',
//       revenueModel: 'Grants and NGO partnerships.',
//       competitors: 'Offline content platforms and local programs.',
//       impact: 'Expands access to quality learning in underserved areas.',
//       image: 'slide3',
//       tags: ['Offline', 'Education', 'Access'],
//       features: ['Syncing', 'Preloaded lessons', 'Progress tracking'],
//       metrics: ['Learners served', 'Sync success rate'],
//       comments: [
//         { id: 'c19', author: 'Omar', message: 'Offline kits would be essential in remote communities.', date: '2026-05-27' },
//       ],
//     },
//     {
//       id: { $oid: '64b2c3d4e5f678901234abdc' },
//       title: 'Neighborhood Energy Grid',
//       category: 'Energy',
//       stage: 'Concept',
//       description: 'Local microgrid orchestration for shared solar and storage.',
//       details: 'Coordinate generation and storage across households to optimize local usage and reduce grid strain.',
//       problem: 'Centralized grids are inefficient for localized renewable assets.',
//       solution: 'Microgrid management with fair billing and optimization.',
//       targetMarket: 'Co-ops and eco communities.',
//       revenueModel: 'Platform licensing and hardware partnerships.',
//       competitors: 'Energy orchestration platforms.',
//       impact: 'Improves renewable utilization and reduces local outages.',
//       image: 'slide1',
//       tags: ['Energy', 'Microgrid', 'Solar'],
//       features: ['Load balancing', 'Fair billing', 'Storage orchestration'],
//       metrics: ['Renewable utilization %', 'Cost savings'],
//       comments: [
//         { id: 'c20', author: 'Ari', message: 'Local microgrids could really help reduce outages.', date: '2026-05-28' },
//       ],
//     },
//   ]

// FEATURED_IDEAS.forEach((idea) => {
//   if (idea.comments === undefined) idea.comments = [];
// });

// const normalize = (v) => {
//   if (typeof v === 'string') return v;
//   if (v && typeof v === 'object') return v.$oid || v.id || JSON.stringify(v);
//   return String(v);
// };

// export const getIdeaById = (id) => FEATURED_IDEAS.find((idea) => normalize(idea.id) === normalize(id));
// export const getAllIdeaIds = () => FEATURED_IDEAS.map((idea) => ({ id: normalize(idea.id) }));
